# Generated by Django 4.0.4 on 2022-09-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Service_Category',
        ),
        migrations.DeleteModel(
            name='Service_Category',
        ),
    ]
