# Generated by Django 4.0.4 on 2022-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0002_remove_services_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='Order_Total',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
            preserve_default=False,
        ),
    ]
