# Generated by Django 4.0.4 on 2022-09-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0003_order_details_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='Order_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
