# Generated by Django 4.0.4 on 2023-02-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0005_wallettransaction_usercredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_request',
            name='Payment_Method',
            field=models.CharField(default='credit', max_length=300),
            preserve_default=False,
        ),
    ]
