# Generated by Django 4.0.4 on 2023-02-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0006_order_request_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('IBAN', models.CharField(max_length=100)),
            ],
        ),
    ]
