# Generated by Django 4.0.4 on 2023-02-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0007_bankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='Paid',
            field=models.CharField(choices=[('paid', 'Paid'), ('not paid', 'Not Paid')], default='not paid', max_length=10),
        ),
    ]
