# Generated by Django 4.0.4 on 2023-02-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0008_alter_order_details_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_request',
            name='Payment_Method',
        ),
        migrations.AddField(
            model_name='order_details',
            name='Payment_Method',
            field=models.CharField(default='credit', max_length=300),
            preserve_default=False,
        ),
    ]
