# Generated by Django 4.0.4 on 2023-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0009_remove_order_request_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='Payment_Method',
            field=models.CharField(choices=[('credit', 'Credit'), ('bank transfer', 'Bank Transfer')], max_length=20),
        ),
    ]
