# Generated by Django 4.0.4 on 2023-02-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0010_alter_order_details_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='Payment_Method',
            field=models.CharField(choices=[('credit', 'Credit'), ('bank transfer', 'Bank Transfer')], default='credit', max_length=20),
        ),
    ]
