# Generated by Django 4.0.4 on 2023-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0011_alter_order_details_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='Status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('to do', 'TO DO')], default='to do', max_length=20),
        ),
    ]
