# Generated by Django 4.0.4 on 2023-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0015_order_request_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='Completion_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
