# Generated by Django 4.0.4 on 2023-02-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0016_order_details_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='Completion_Date',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='Status',
        ),
        migrations.AddField(
            model_name='order_request',
            name='Completion_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order_request',
            name='Status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('to do', 'TO DO')], default='to do', max_length=20),
        ),
    ]
