# Generated by Django 4.0.4 on 2023-03-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0018_user_profile_vat_user_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Selling_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sites',
            name='Selling_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='randomapp.site_selling_category'),
        ),
    ]
