# Generated by Django 4.0.4 on 2023-03-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0019_site_selling_category_sites_selling_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
