# Generated by Django 4.0.4 on 2023-03-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0020_sites_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_request',
            name='Completion_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
