# Generated by Django 4.0.4 on 2023-03-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0021_alter_order_request_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='Payment_Method',
            field=models.CharField(choices=[('wallet credit', 'Wallet Credit'), ('bank transfer', 'Bank Transfer')], default='wallet credit', max_length=20),
        ),
    ]
