# Generated by Django 4.0.4 on 2023-03-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0022_alter_order_details_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='VAT',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
