# Generated by Django 4.0.4 on 2023-03-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0023_alter_user_profile_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='VAT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
