# Generated by Django 4.0.4 on 2023-03-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0024_alter_user_profile_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='VAT',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
