# Generated by Django 4.0.4 on 2023-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0025_alter_billing_details_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='ACH_Routing',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'eur'), ('POUND', 'pound')], default='usd', max_length=20),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='note',
            field=models.TextField(default='This is a note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
    ]
